version: '3'
services:
  frontend:
    build:
      context:  ./
      dockerfile: newsapp/Dockerfile
    ports:
      - "3000:3000"  
  backend:
    build:
      context: ./
      dockerfile: backend/Dockerfile
    ports:
      - "8080:8080"  
